[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { fg = "black", bg = "#BBBBBB" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightyellow", bg = "lightyellow" }
marker_selected = { fg = "lightblue",   bg = "lightblue" }

# Tab
tab_active   = { fg = "black", bg = "white" }
tab_inactive = { fg = "white", bg = "darkgray" }
tab_width    = 1

# Count
count_copied   = { fg = "black", bg = "lightgreen" }
count_cut      = { fg = "black", bg = "lightred" }
count_selected = { fg = "black", bg = "lightblue" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }
